"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { ContentType, SearchIndexItem } from "@/lib/types";
import { CONTENT_TYPE_LABELS, filterSearchIndex } from "@/lib/searchUtils";

const TYPE_FILTERS: (ContentType | "all")[] = ["all", "article", "variety", "guide", "shop"];

export default function SearchClient({ initialQuery = "" }: { initialQuery?: string }) {
  const [index, setIndex] = useState<SearchIndexItem[] | null>(null);
  const [query, setQuery] = useState(initialQuery);
  const [type, setType] = useState<ContentType | "all">("all");

  useEffect(() => {
    // Static file generated by scripts/build-search-index.mjs — not an API
    // route, just a plain asset under /public.
    fetch("/search-index.json")
      .then((res) => res.json())
      .then(setIndex)
      .catch(() => setIndex([]));
  }, []);

  const results = useMemo(() => {
    if (!index) return [];
    return filterSearchIndex(index, query, type);
  }, [index, query, type]);

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center gap-2.5 rounded-xl border border-border bg-white px-4 py-3.5">
        <span className="text-ink-fainter text-lg">⌕</span>
        <input
          autoFocus
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="ค้นหาบทความ สายพันธุ์ ร้านค้า หรือคู่มือ..."
          className="w-full border-none bg-transparent text-[16px] text-ink outline-none"
        />
      </div>

      <div className="flex flex-wrap gap-2">
        {TYPE_FILTERS.map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setType(t)}
            className={`rounded-full border px-4 py-2 text-sm font-medium ${
              type === t
                ? "border-avocado bg-avocado text-white"
                : "border-border bg-white text-ink-soft hover:border-avocado hover:text-avocado"
            }`}
          >
            {t === "all" ? "ทั้งหมด" : CONTENT_TYPE_LABELS[t]}
          </button>
        ))}
      </div>

      {index === null ? (
        <p className="text-sm text-ink-faint">กำลังโหลด...</p>
      ) : query.trim() === "" ? (
        <p className="text-sm text-ink-faint">พิมพ์คำค้นหาด้านบนเพื่อค้นทั่วทั้งเว็บ</p>
      ) : results.length === 0 ? (
        <p className="rounded-xl border border-border bg-beige px-5 py-4 text-[15px] text-ink-faint">
          ไม่พบผลลัพธ์สำหรับ “{query}”
        </p>
      ) : (
        <ul className="flex flex-col gap-3">
          {results.map((item) => (
            <li key={`${item.type}-${item.id}`}>
              <Link
                href={item.url}
                className="flex flex-col gap-1 rounded-xl border border-border bg-white p-5 hover:border-avocado-light"
              >
                <div className="flex items-center gap-2 text-[13px] text-ink-faint">
                  <span className="rounded-full bg-avocado-pale px-2.5 py-0.5 font-semibold text-avocado">
                    {CONTENT_TYPE_LABELS[item.type]}
                  </span>
                </div>
                <span className="font-display text-[17px] font-semibold text-avocado-dark">
                  {item.title}
                </span>
                <span className="line-clamp-2 text-sm text-ink-muted">{item.excerpt}</span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
